<?php
// Automatically Generated by TestLink Installer
define('DB_TYPE', 'mysql');
define('DB_USER', '@{testlink.db.user}');
define('DB_PASS', '%{TESTLINK_DB_PASSWORD}');
define('DB_HOST', '@{mysql.host}:@{mysql.port}');
define('DB_NAME', '@{testlink.db.name}');
define('DB_TABLE_PREFIX', '');
?>