cas:
  authn:
    attribute-repository:
      stub:
        attributes:
          '@{cas.attr.dn}': '@{cas.attr.dn}'
          '@{cas.attr.uid}': '@{cas.attr.uid}'
          '@{cas.attr.commonname}': '@{cas.attr.commonname}'
          '@{cas.attr.displayname}': '@{cas.attr.displayname}'
          '@{cas.attr.firstname}': '@{cas.attr.firstname}'
          '@{cas.attr.lastname}': '@{cas.attr.lastname}'
          '@{cas.attr.mail}': '@{cas.attr.mail}'
          '@{cas.attr.telephone}': '@{cas.attr.telephone}'
          '@{cas.attr.organization}': '@{cas.attr.organization}'
          '@{cas.attr.groups}': '@{cas.attr.groups}'
  mgmt:
    admin-roles: '@{product.group.admins}'
    authz-attributes: '@{cas.attr.groups}'
    default-locale: '@{cas.lang}'
    server-name: '@{product.scheme}://@{product.domain}'
  server:
    name: 'https://@{cas.host}'
    prefix: '${cas.server.name}@{cas.context}'
  service-registry:
    json:
      location: 'file://@{product.data}/services/cas/services'
