server:
  port: @{package.port.http}
security:
  user:
    name: @{root.user}
    password: %{ROOT_PASSWORD}
    role: USER,ADMIN
  oauth2:
    client:
      accessTokenUri: @{cas.url}oauth2.0/accessToken
      userAuthorizationUri: @{cas.url}oauth2.0/authorize
      clientId: @{product.id}-manager
      clientSecret: %{MANAGER_OAUTH_PASSWORD}
    resource:
      userInfoUri: @{cas.url}oauth2.0/profile
      preferTokenInfo: false
    logout:
      userLogoutUri: @{cas.url}logout
      redirectParam: service
      redirectUri: @{product.scheme}://@{product.domain}/manager/
logging:
  path: @{package.log}
zuul:
  routes:
    api-v1:
      path: /v1/**
      url: http://@{api.host}:@{api.port.http}/api/v1
